disabled_rules: # rule identifiers to exclude from running
  - nesting
  - unused_closure_parameter
  - xctfail_message
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
identifier_name:
  min_length: 2
